"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import Header from "../../components/Header";
import AuthGuard from "../../components/AuthGuard";
import {supabaseBrowser} from "../../lib/supabase-browser";
const money=new Intl.NumberFormat("vi-VN");const labels:any={pending:"Chờ xác nhận",confirmed:"Đã xác nhận",shipping:"Đang giao",delivered:"Đã giao",cancelled:"Đã hủy"};
export default function SellerOrdersPage(){
 const[orders,setOrders]=useState<any[]>([]),[loading,setLoading]=useState(true);
 async function load(){const{data:{user}}=await supabaseBrowser.auth.getUser();if(!user){setLoading(false);return}const{data,error}=await supabaseBrowser.from("orders").select("id,order_code,buyer_id,grand_total,customer_name,customer_phone,shipping_address,status,created_at").eq("seller_id",user.id).order("created_at",{ascending:false});if(!error)setOrders(data||[]);setLoading(false)}
 useEffect(()=>{load()},[]);
 async function status(id:string,status:string){const{data,error}=await supabaseBrowser.functions.invoke("order-actions",{body:{action:"update_status",order_id:id,status}});if(error||data?.error){alert(data?.error||error?.message);return}load()}
 return <AuthGuard><main><Header/><section className="container-page py-8"><div className="card p-6 md:p-8"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-sm font-extrabold uppercase tracking-widest text-brand-600">Nhà bán hàng</p><h1 className="mt-1 text-3xl font-black">Quản lý đơn hàng</h1><p className="mt-2 text-sm text-slate-500">Chỉ hiển thị đơn thuộc tài khoản nhà bán hàng đang đăng nhập.</p></div><Link href="/tai-khoan" className="rounded-xl border px-4 py-2.5 text-sm font-extrabold">← Tài khoản</Link></div>{loading?<p className="py-12 text-center text-slate-500">Đang tải...</p>:!orders.length?<div className="py-12 text-center text-slate-500">Chưa có đơn hàng.</div>:<div className="mt-6 divide-y">{orders.map(o=><div key={o.id} className="py-5"><div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div><p className="font-black">{o.order_code}</p><p className="mt-1 text-sm text-slate-500">{new Date(o.created_at).toLocaleString("vi-VN")}</p><p className="mt-2 text-sm">Khách: <b>{o.customer_name}</b> · {o.customer_phone}</p><p className="mt-1 text-sm text-slate-500">{o.shipping_address}</p><p className="mt-2 text-lg font-black text-brand-700">{money.format(o.grand_total)} đ · COD</p></div><div className="flex flex-wrap items-center gap-2"><span className="rounded-full bg-brand-50 px-3 py-1 text-xs font-extrabold text-brand-700">{labels[o.status]||o.status}</span>{o.status==="pending"&&<button onClick={()=>status(o.id,"confirmed")} className="rounded-lg bg-brand-600 px-3 py-2 text-xs font-extrabold text-white">Xác nhận</button>}{o.status==="confirmed"&&<button onClick={()=>status(o.id,"shipping")} className="rounded-lg bg-brand-600 px-3 py-2 text-xs font-extrabold text-white">Bắt đầu giao</button>}{o.status==="shipping"&&<button onClick={()=>status(o.id,"delivered")} className="rounded-lg bg-brand-600 px-3 py-2 text-xs font-extrabold text-white">Đã giao</button>}{!["delivered","cancelled"].includes(o.status)&&<button onClick={()=>status(o.id,"cancelled")} className="rounded-lg bg-red-50 px-3 py-2 text-xs font-extrabold text-red-600">Hủy</button>}</div></div></div>)}</div>}</div></section></main></AuthGuard>
}