"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import Header from "../../components/Header";
import AuthGuard from "../../components/AuthGuard";
import {supabaseBrowser} from "../../lib/supabase-browser";
const money=new Intl.NumberFormat("vi-VN");
export default function CheckoutPage(){
 const[cart,setCart]=useState<any[]>([]),[name,setName]=useState(""),[phone,setPhone]=useState(""),[address,setAddress]=useState(""),[note,setNote]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");
 useEffect(()=>{try{setCart(JSON.parse(localStorage.getItem("ptmarket-cart")||"[]"))}catch{};supabaseBrowser.auth.getUser().then(({data})=>{const u=data.user;if(u){setName(u.user_metadata?.full_name||"");setPhone(u.user_metadata?.phone||"")}})},[]);
 const total=cart.reduce((s,i)=>s+(i.price_type==="contact"?0:(i.price||0)*i.quantity),0);
 async function submit(){if(!cart.length){setError("Giỏ hàng đang trống.");return}if(!name.trim()||!phone.trim()||!address.trim()){setError("Vui lòng nhập đủ họ tên, số điện thoại và địa chỉ.");return}setBusy(true);setError("");for(const i of cart){if(i.price_type==="contact"){setError("Sản phẩm "+i.title+" đang để giá liên hệ, chưa thể đặt online.");setBusy(false);return}const{data,error:e}=await supabaseBrowser.functions.invoke("order-actions",{body:{action:"create",listing_id:i.id,quantity:i.quantity,customer_name:name,customer_phone:phone,shipping_address:address,note}});if(e||data?.error){setError(data?.error||e?.message||"Không thể tạo đơn hàng.");setBusy(false);return}}localStorage.removeItem("ptmarket-cart");window.location.href="/don-hang"}
 return <AuthGuard><main><Header/><section className="container-page py-8"><div className="mx-auto max-w-2xl card p-6 md:p-8"><Link href="/gio-hang" className="text-sm font-bold text-brand-700">← Quay lại giỏ hàng</Link><h1 className="mt-3 text-3xl font-black">Thông tin đặt hàng</h1><p className="mt-2 text-sm text-slate-500">Thanh toán khi nhận hàng (COD).</p>{error&&<p className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}<div className="mt-6 grid gap-4"><label className="text-sm font-bold">Họ và tên<input value={name} onChange={e=>setName(e.target.value)} className="mt-1 w-full rounded-xl border px-3 py-3"/></label><label className="text-sm font-bold">Số điện thoại<input value={phone} onChange={e=>setPhone(e.target.value)} className="mt-1 w-full rounded-xl border px-3 py-3"/></label><label className="text-sm font-bold">Địa chỉ nhận hàng<textarea value={address} onChange={e=>setAddress(e.target.value)} className="mt-1 min-h-24 w-full rounded-xl border px-3 py-3"/></label><label className="text-sm font-bold">Ghi chú<textarea value={note} onChange={e=>setNote(e.target.value)} className="mt-1 min-h-20 w-full rounded-xl border px-3 py-3"/></label></div><div className="mt-6 rounded-2xl bg-slate-50 p-4"><p className="font-black">Tổng tiền: <span className="text-brand-700">{money.format(total)} đ</span></p><p className="mt-1 text-xs text-slate-500">{cart.length} sản phẩm trong giỏ. Nếu có nhiều nhà bán hàng, hệ thống tạo đơn riêng theo từng sản phẩm.</p></div><button disabled={busy} onClick={submit} className="mt-5 w-full rounded-xl bg-brand-600 px-4 py-3 font-extrabold text-white disabled:opacity-50">{busy?"Đang tạo đơn...":"Đặt hàng COD"}</button></div></section></main></AuthGuard>
}