import Link from "next/link";
import {ArrowRight,MapPin,ShieldCheck,Smartphone,Store,Zap} from "lucide-react";
import Header from "../components/Header";import SearchBox from "../components/SearchBox";import CategoryCard from "../components/CategoryCard";import {getSupabase} from "../lib/supabase";
type Category={id:string;name:string;slug:string;icon:string|null};type Listing={id:string;title:string;price:number;images:string[]|null;condition:string};
const demo:Listing[]=[
{id:"demo1",title:"iPhone 15 Pro 256GB - máy đẹp, pin tốt",price:15900000,condition:"used",images:["https://images.unsplash.com/photo-1592899677977-9c10ca588bbd?auto=format&fit=crop&w=900&q=80"]},
{id:"demo2",title:"MacBook Air M2 13 inch - chính chủ",price:18900000,condition:"like_new",images:["https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=900&q=80"]},
{id:"demo3",title:"PC Gaming i5 + RTX - chiến game mượt",price:12500000,condition:"used",images:["https://images.unsplash.com/photo-1593640408182-31c70c8268f5?auto=format&fit=crop&w=900&q=80"]},
{id:"demo4",title:"Laptop văn phòng 14 inch, RAM 16GB",price:8200000,condition:"used",images:["https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=900&q=80"]}];
const money=new Intl.NumberFormat("vi-VN");
export default async function Home(){const sb=getSupabase();let categories:Category[]=[];let listings:Listing[]=[];if(sb){const[c,l]=await Promise.all([sb.from("categories").select("id,name,slug,icon").order("name"),sb.from("listings").select("id,title,price,images,condition").eq("status","published").order("created_at",{ascending:false}).limit(8)]);categories=(c.data||[]) as Category[];listings=(l.data||[]) as Listing[]}
const products=listings.length?listings:demo;
return <main><Header/>
<section className="relative overflow-hidden bg-slate-900"><div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(4,35,24,.94),rgba(4,35,24,.56),rgba(4,35,24,.18)),url('https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=1800&q=85')] bg-cover bg-center"/><div className="relative container-page py-20 md:py-28"><div className="max-w-2xl text-white"><div className="mb-4 inline-flex items-center gap-2 rounded-full bg-white/10 px-3 py-1.5 text-xs font-bold ring-1 ring-white/20"><MapPin size={14}/>Mua bán tại Phú Thọ</div><h1 className="text-balance text-4xl font-black leading-tight md:text-6xl">Mua bán, dịch vụ và địa điểm tại Phú Thọ</h1><p className="mt-5 max-w-xl text-base leading-7 text-white/80 md:text-lg">Tập trung vào điện thoại, laptop, PC, linh kiện và các sản phẩm địa phương. Tìm người bán gần bạn, nhanh và dễ.</p><div className="mt-7"><SearchBox/></div></div></div></section>
<section id="danh-muc" className="container-page py-10 md:py-14"><div className="mb-6 flex items-end justify-between gap-4"><div><p className="text-sm font-extrabold uppercase tracking-widest text-brand-600">Khám phá</p><h2 className="mt-1 text-2xl font-black md:text-3xl">Danh mục phổ biến</h2></div><span className="shrink-0 text-sm font-bold text-slate-400">{categories.length} danh mục</span></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-3 md:grid-cols-5">{[...categories.filter(c=>c.slug==="quan-an"),...categories.filter(c=>c.slug!=="quan-an" && ["dien-thoai","laptop","pc-may-tinh","linh-kien-may-tinh","man-hinh","may-tinh-bang","phu-kien-cong-nghe","dien-thoai-may-tinh","xe-may-o-to","nha-dat"].includes(c.slug))].slice(0,10).map(c=><CategoryCard key={c.id} category={c}/>)}</div></section>
<section className="container-page pb-12"><div className="grid gap-5 lg:grid-cols-[1fr_300px]"><div><div className="mb-5 flex items-end justify-between"><div><p className="text-sm font-extrabold uppercase tracking-widest text-brand-600">Công nghệ</p><h2 className="mt-1 text-2xl font-black">Tin điện thoại & máy tính</h2></div><Link href="/tim-kiem?q=điện%20thoại" className="text-sm font-bold text-brand-700">Xem thêm →</Link></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{products.map(item=><Link key={item.id} href={item.id.startsWith("demo")?"#":"/tin?id="+item.id} className="group min-w-0 overflow-hidden rounded-2xl border bg-white transition hover:-translate-y-1 hover:shadow-soft"><div className="aspect-[4/3] overflow-hidden bg-slate-100"><img src={item.images?.[0]} alt="" className="h-full w-full object-cover transition duration-500 group-hover:scale-105"/></div><div className="p-4"><h3 className="line-clamp-2 min-h-10 break-words text-sm font-bold leading-5">{item.title}</h3><p className="mt-2 text-lg font-black text-brand-700">{money.format(item.price)} đ</p><div className="mt-2 flex items-center justify-between text-xs text-slate-500"><span>{item.condition==="like_new"?"Như mới":"Đã sử dụng"}</span><span>Phú Thọ</span></div></div></Link>)}</div></div>
<aside className="space-y-4"><div className="rounded-2xl bg-brand-700 p-6 text-white shadow-soft"><Zap size={28}/><h3 className="mt-4 text-xl font-black">Đăng tin miễn phí</h3><p className="mt-2 text-sm leading-6 text-white/80">Đăng bán iPhone, Samsung, laptop, PC, màn hình và linh kiện.</p><Link href="/dang-tin" className="mt-5 inline-flex rounded-xl bg-white px-4 py-2.5 text-sm font-extrabold text-brand-700">Đăng tin ngay</Link></div><div id="khu-vuc" className="card p-5"><h3 className="font-black">Khu vực Phú Thọ</h3><div className="mt-4 grid grid-cols-2 gap-2 text-sm">{["Việt Trì","Lâm Thao","Phù Ninh","Thanh Ba","Đoan Hùng","Hạ Hòa","Cẩm Khê","Thanh Sơn","Tân Sơn","Yên Lập"].map(x=><Link key={x} href={"/khu-vuc?slug="+({"Việt Trì":"viet-tri","Lâm Thao":"lam-thao","Phù Ninh":"phu-ninh","Thanh Ba":"thanh-ba","Đoan Hùng":"doan-hung","Hạ Hòa":"ha-hoa","Cẩm Khê":"cam-khe","Thanh Sơn":"thanh-son","Tân Sơn":"tan-son","Yên Lập":"yen-lap"} as Record<string,string>)[x]} className="rounded-lg bg-slate-50 px-3 py-2 font-semibold text-slate-600 hover:bg-brand-50 hover:text-brand-700">{x}</Link>)}</div></div></aside></div></section>
<section className="border-y bg-brand-50"><div className="container-page grid gap-8 py-10 md:grid-cols-3">{[{i:Smartphone,t:"Ưu tiên đồ công nghệ",d:"Tối ưu trải nghiệm tìm kiếm điện thoại, laptop, PC và linh kiện."},{i:ShieldCheck,t:"Dữ liệu an toàn",d:"Supabase Auth và RLS giúp kiểm soát dữ liệu tài khoản và tin đăng."},{i:Store,t:"Đúng cộng đồng địa phương",d:"Kết nối người mua và người bán trong cùng khu vực Phú Thọ."}].map(({i:Icon,t,d})=><div key={t} className="flex gap-4"><div className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-white text-brand-600"><Icon size={21}/></div><div><h3 className="font-extrabold">{t}</h3><p className="mt-1 text-sm leading-6 text-slate-600">{d}</p></div></div>)}</div></section>
<footer className="bg-white"><div className="container-page py-10"><div className="grid gap-8 md:grid-cols-3"><div><div className="font-black text-lg">PHÚ THỌ MARKET</div><p className="mt-3 max-w-sm text-sm leading-6 text-slate-500">Chợ online địa phương tập trung điện thoại, máy tính và các sản phẩm tại Phú Thọ.</p></div><div><h3 className="font-black">Khám phá</h3><div className="mt-3 grid gap-2 text-sm text-slate-500"><Link href="#danh-muc">Danh mục</Link><Link href="#khu-vuc">Khu vực</Link><Link href="/dang-tin">Đăng tin</Link></div></div><div><h3 className="font-black">Phát triển</h3><p className="mt-3 text-sm leading-6 text-slate-500">MVP đã kết nối nền tảng Supabase; tiếp theo sẽ hoàn thiện Auth, Storage, tìm kiếm và quản trị.</p></div></div></div><div className="border-t py-5 text-center text-xs text-slate-400">© 2026 Phú Thọ Market</div></footer></main>}