"use client";
import {useEffect,useMemo,useState} from "react";
import Link from "next/link";
import Header from "../../components/Header";
import AuthGuard from "../../components/AuthGuard";
import {Minus,Plus,Trash2,ShoppingCart} from "lucide-react";
const money=new Intl.NumberFormat("vi-VN");
export default function CartPage(){
 const[cart,setCart]=useState<any[]>([]),[loading,setLoading]=useState(true);
 function load(){try{setCart(JSON.parse(localStorage.getItem("ptmarket-cart")||"[]"))}catch{setCart([])}setLoading(false)}
 useEffect(()=>{load();const fn=()=>load();window.addEventListener("ptmarket-cart-updated",fn);return()=>window.removeEventListener("ptmarket-cart-updated",fn)},[]);
 function save(next:any[]){setCart(next);localStorage.setItem("ptmarket-cart",JSON.stringify(next));window.dispatchEvent(new Event("ptmarket-cart-updated"))}
 function qty(id:string,n:number){save(cart.map(i=>i.id===id?{...i,quantity:Math.max(0,n)}:i).filter(i=>i.quantity>0))}
 const total=useMemo(()=>cart.reduce((s,i)=>s+(i.price_type==="contact"?0:(i.price||0)*i.quantity),0),[cart]);
 if(loading)return <main><Header/><section className="container-page py-12 text-center text-slate-500">Đang tải giỏ hàng...</section></main>;
 return <AuthGuard><main><Header/><section className="container-page py-8"><div className="card p-6 md:p-8"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-sm font-extrabold uppercase tracking-widest text-brand-600">Mua hàng</p><h1 className="mt-1 text-3xl font-black">Giỏ hàng</h1></div><Link href="/don-hang" className="rounded-xl border px-4 py-2.5 text-sm font-extrabold">📦 Đơn hàng của tôi</Link></div>{!cart.length?<div className="py-14 text-center"><ShoppingCart className="mx-auto text-slate-300" size={48}/><p className="mt-3 font-bold text-slate-500">Giỏ hàng đang trống.</p><Link href="/danh-muc" className="mt-4 inline-block rounded-xl bg-brand-600 px-4 py-2.5 text-sm font-extrabold text-white">Xem sản phẩm</Link></div>:<><div className="mt-6 divide-y">{cart.map(i=><div key={i.id} className="flex flex-col gap-4 py-5 sm:flex-row sm:items-center"><Link href={"/tin?id="+i.id} className="h-24 w-28 shrink-0 overflow-hidden rounded-xl bg-slate-100">{i.image&&<img src={i.image} alt="" className="h-full w-full object-cover"/>}</Link><div className="min-w-0 flex-1"><Link href={"/tin?id="+i.id} className="font-black hover:text-brand-700">{i.title}</Link><p className="mt-1 text-sm font-extrabold text-brand-700">{i.price_type==="contact"?"Liên hệ":money.format(i.price)+" đ"}</p><div className="mt-3 inline-flex items-center rounded-xl border"><button onClick={()=>qty(i.id,i.quantity-1)} className="grid h-9 w-9 place-items-center"><Minus size={15}/></button><span className="min-w-10 text-center font-black">{i.quantity}</span><button onClick={()=>qty(i.id,i.quantity+1)} className="grid h-9 w-9 place-items-center text-brand-700"><Plus size={15}/></button></div></div><div className="flex items-center gap-3"><p className="font-black">{i.price_type==="contact"?"Liên hệ":money.format((i.price||0)*i.quantity)+" đ"}</p><button onClick={()=>qty(i.id,0)} className="rounded-lg bg-red-50 p-2 text-red-600" aria-label="Xóa"><Trash2 size={17}/></button></div></div>)}</div><div className="mt-5 flex flex-col gap-4 border-t pt-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm text-slate-500">Tổng tiền</p><p className="text-2xl font-black text-brand-700">{money.format(total)} đ</p></div><Link href="/dat-hang" className="rounded-xl bg-brand-600 px-5 py-3 text-center text-sm font-extrabold text-white">Tiến hành đặt hàng</Link></div></>}</div></section></main></AuthGuard>
}