"use client";
import {useEffect,useState} from "react";import Link from "next/link";import Header from "../../components/Header";import {Heart,MessageCircle,Phone,Flag} from "lucide-react";import {supabaseBrowser} from "../../lib/supabase-browser";
const money=new Intl.NumberFormat("vi-VN");
export default function ListingDetailPage(){
 const[x,setX]=useState<any>(null),[loading,setLoading]=useState(true),[fav,setFav]=useState(false),[user,setUser]=useState<any>(null),[saving,setSaving]=useState(false);
 async function init(){const id=new URLSearchParams(window.location.search).get("id");const{data:{user:u}}=await supabaseBrowser.auth.getUser();setUser(u);if(!id){setLoading(false);return}
  const{data}=await supabaseBrowser.from("listings").select("id,title,description,price,images,condition,phone,created_at,views,expires_at,seller_id,specs,locations(name),categories(name),profiles(full_name)").eq("id",id).eq("status","published").maybeSingle();setX(data);setLoading(false);
  if(u&&data){const{data:f}=await supabaseBrowser.from("favorites").select("listing_id").eq("user_id",u.id).eq("listing_id",id).maybeSingle();setFav(!!f)}
  if(data) await supabaseBrowser.from("listings").update({views:(data.views||0)+1}).eq("id",data.id);
 }
 useEffect(()=>{init()},[]);
 async function toggleFavorite(){if(!user){window.location.href="/dang-nhap";return}if(!x)return;setSaving(true);if(fav){await supabaseBrowser.from("favorites").delete().eq("user_id",user.id).eq("listing_id",x.id);setFav(false)}else{await supabaseBrowser.from("favorites").insert({user_id:user.id,listing_id:x.id});setFav(true)}setSaving(false)}
 if(loading)return <main><Header/><section className="container-page py-12 text-center text-slate-500">Đang tải tin...</section></main>;
 if(!x)return <main><Header/><section className="container-page py-12 text-center"><h1 className="text-2xl font-black">Không tìm thấy tin</h1><Link href="/" className="mt-4 inline-block font-bold text-brand-700">← Về trang chủ</Link></section></main>;
 return <main><Header/><section className="container-page py-8"><Link href="/tim-kiem" className="text-sm font-bold text-brand-700">← Quay lại tìm kiếm</Link><div className="mt-5 grid gap-6 lg:grid-cols-[1fr_360px]"><div className="card overflow-hidden"><div className="grid grid-cols-2 gap-2 bg-slate-100 p-2">{(x.images||[]).map((src:string,i:number)=><img key={i} src={src} alt="" className="aspect-square w-full rounded-xl object-cover"/>)}</div><div className="p-6"><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-bold text-brand-600">{x.categories?.name||"Công nghệ"}</p><h1 className="mt-2 text-2xl font-black">{x.title}</h1></div><button disabled={saving} onClick={toggleFavorite} aria-label="Yêu thích" className={"grid h-11 w-11 shrink-0 place-items-center rounded-xl border "+(fav?"bg-red-50 text-red-500":"bg-white text-slate-500")}><Heart size={21} fill={fav?"currentColor":"none"}/></button></div><p className="mt-3 text-2xl font-black text-brand-700">{money.format(x.price)} đ</p><div className="mt-4 flex flex-wrap gap-2 text-xs text-slate-500"><span className="rounded-full bg-slate-100 px-3 py-1">{x.condition==="new"?"Mới":x.condition==="like_new"?"Như mới":"Đã sử dụng"}</span><span className="rounded-full bg-slate-100 px-3 py-1">📍 {x.locations?.name||"Phú Thọ"}</span><span className="rounded-full bg-slate-100 px-3 py-1">👁 {x.views||0} lượt xem</span></div>{x.description&&<p className="mt-6 whitespace-pre-wrap leading-7 text-slate-600">{x.description}</p>}{x.specs&&Object.keys(x.specs).length>0&&<div className="mt-7"><h2 className="font-black">Thông số kỹ thuật</h2><div className="mt-3 grid gap-2 sm:grid-cols-2">{Object.entries(x.specs).map(([k,v])=><div key={k} className="rounded-xl bg-slate-50 p-3 text-sm"><span className="text-slate-500">{k}</span><b className="ml-2">{String(v)}</b></div>)}</div></div>}</div></div><aside className="card h-fit p-6"><h2 className="text-lg font-black">Thông tin người bán</h2><p className="mt-4 font-bold">{x.profiles?.full_name||"Người bán"}</p><p className="mt-2 text-sm text-slate-500">📍 {x.locations?.name||"Phú Thọ"}</p>{x.phone&&<a href={"tel:"+x.phone} className="mt-5 flex items-center justify-center gap-2 rounded-xl bg-brand-600 px-4 py-3 text-center font-extrabold text-white"><Phone size={17}/>Gọi {x.phone}</a>}<Link href={"/tin-nhan?listing="+x.id+"&seller="+x.seller_id} className="mt-2 flex items-center justify-center gap-2 rounded-xl border px-4 py-3 text-center font-extrabold"><MessageCircle size={17}/>Nhắn tin</Link><button onClick={()=>alert("Cảm ơn bạn. Chức năng xử lý báo cáo sẽ được quản trị viên tiếp nhận.")} className="mt-3 flex w-full items-center justify-center gap-2 text-xs font-bold text-slate-400"><Flag size={14}/>Báo cáo tin</button></aside></div></section></main>
}