"use client";
import {useEffect,useState} from "react";import Link from "next/link";import Header from "../../components/Header";import {Heart,MessageCircle,Phone,ChevronLeft,ChevronRight} from "lucide-react";import ReportButton from "../../components/ReportButton";import {supabaseBrowser} from "../../lib/supabase-browser";
const money=new Intl.NumberFormat("vi-VN");
const specLabels:Record<string,string>={brand:"Hãng",model:"Model",cpu:"CPU",ram:"RAM",storage:"Bộ nhớ",gpu:"GPU",screen:"Màn hình",battery:"Pin",warranty:"Bảo hành"};
export default function ListingDetailPage(){
 const[x,setX]=useState<any>(null),[loading,setLoading]=useState(true),[fav,setFav]=useState(false),[user,setUser]=useState<any>(null),[saving,setSaving]=useState(false),[active,setActive]=useState(0);
 async function init(){const id=new URLSearchParams(window.location.search).get("id");const{data:{user:u}}=await supabaseBrowser.auth.getUser();setUser(u);if(!id){setLoading(false);return}
  const{data}=await supabaseBrowser.from("listings").select("id,title,description,price,images,condition,phone,created_at,views,expires_at,seller_id,specs,locations(name),categories(name),profiles(full_name)").eq("id",id).eq("status","published").or("expires_at.is.null,expires_at.gt."+new Date().toISOString()).maybeSingle();setX(data);setLoading(false);
  if(u&&data){const{data:f}=await supabaseBrowser.from("favorites").select("listing_id").eq("user_id",u.id).eq("listing_id",id).maybeSingle();setFav(!!f)}
  if(data) await supabaseBrowser.rpc("increment_listing_views",{p_listing_id:data.id});
 }
 useEffect(()=>{init()},[]);
 async function toggleFavorite(){if(!user){window.location.href="/dang-nhap";return}if(!x)return;setSaving(true);if(fav){await supabaseBrowser.from("favorites").delete().eq("user_id",user.id).eq("listing_id",x.id);setFav(false)}else{const r=await supabaseBrowser.from("favorites").insert({user_id:user.id,listing_id:x.id});if(!r.error)setFav(true)}setSaving(false)}
 if(loading)return <main><Header/><section className="container-page py-12 text-center text-slate-500">Đang tải tin...</section></main>;
 if(!x)return <main><Header/><section className="container-page py-12 text-center"><h1 className="text-2xl font-black">Không tìm thấy tin</h1><Link href="/" className="mt-4 inline-block font-bold text-brand-700">← Về trang chủ</Link></section></main>;
 const images=(x.images||[]).filter(Boolean);const current=images[active]||"";
 return <main><Header/><section className="container-page py-8"><Link href="/tim-kiem" className="text-sm font-bold text-brand-700">← Quay lại tìm kiếm</Link><div className="mt-5 grid gap-6 lg:grid-cols-[1fr_360px]"><div className="card overflow-hidden">
  <div className="relative bg-slate-100">{current?<img src={current} alt={x.title} className="aspect-[4/3] w-full object-contain"/>:<div className="grid aspect-[4/3] place-items-center text-slate-400">Không có ảnh</div>}{images.length>1&&<><button aria-label="Ảnh trước" onClick={()=>setActive((active-1+images.length)%images.length)} className="absolute left-3 top-1/2 grid h-10 w-10 -translate-y-1/2 place-items-center rounded-full bg-white/90 shadow"><ChevronLeft size={20}/></button><button aria-label="Ảnh sau" onClick={()=>setActive((active+1)%images.length)} className="absolute right-3 top-1/2 grid h-10 w-10 -translate-y-1/2 place-items-center rounded-full bg-white/90 shadow"><ChevronRight size={20}/></button></>}</div>
  {images.length>1&&<div className="flex gap-2 overflow-x-auto bg-slate-50 p-3">{images.map((src:string,i:number)=><button key={i} onClick={()=>setActive(i)} className={"h-16 w-20 shrink-0 overflow-hidden rounded-lg border-2 "+(active===i?"border-brand-500":"border-transparent")}><img src={src} alt="" className="h-full w-full object-cover"/></button>)}</div>}
  <div className="p-6"><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-bold text-brand-600">{x.categories?.name||"Công nghệ"}</p><h1 className="mt-2 text-2xl font-black">{x.title}</h1></div><button disabled={saving} onClick={toggleFavorite} aria-label="Yêu thích" className={"grid h-11 w-11 shrink-0 place-items-center rounded-xl border "+(fav?"bg-red-50 text-red-500":"bg-white text-slate-500")}><Heart size={21} fill={fav?"currentColor":"none"}/></button></div><p className="mt-3 text-2xl font-black text-brand-700">{money.format(x.price)} đ</p><div className="mt-4 flex flex-wrap gap-2 text-xs text-slate-500"><span className="rounded-full bg-slate-100 px-3 py-1">{x.condition==="new"?"Mới":x.condition==="like_new"?"Như mới":"Đã sử dụng"}</span><span className="rounded-full bg-slate-100 px-3 py-1">📍 {x.locations?.name||"Phú Thọ"}</span><span className="rounded-full bg-slate-100 px-3 py-1">👁 {(x.views||0)+1} lượt xem</span></div>{x.description&&<p className="mt-6 whitespace-pre-wrap leading-7 text-slate-600">{x.description}</p>}{x.specs&&Object.keys(x.specs).length>0&&<div className="mt-7"><h2 className="font-black">Thông số kỹ thuật</h2><div className="mt-3 grid gap-2 sm:grid-cols-2">{Object.entries(x.specs).map(([k,v])=><div key={k} className="rounded-xl bg-slate-50 p-3 text-sm"><span className="text-slate-500">{specLabels[k]||k}</span><b className="ml-2">{String(v)}</b></div>)}</div></div>}</div></div>
  <aside className="card h-fit p-6"><h2 className="text-lg font-black">Thông tin người bán</h2><p className="mt-4 font-bold">{x.profiles?.full_name||"Người bán"}</p><p className="mt-2 text-sm text-slate-500">📍 {x.locations?.name||"Phú Thọ"}</p>{x.phone&&<a href={"tel:"+x.phone} className="mt-5 flex items-center justify-center gap-2 rounded-xl bg-brand-600 px-4 py-3 text-center font-extrabold text-white"><Phone size={17}/>Gọi {x.phone}</a>}<Link href={"/tin-nhan?listing="+x.id+"&seller="+x.seller_id} className="mt-2 flex items-center justify-center gap-2 rounded-xl border px-4 py-3 text-center font-extrabold"><MessageCircle size={17}/>Nhắn tin</Link><div className="mt-4 text-center"><ReportButton listingId={x.id}/></div></aside>
 </div></section></main>
}